language: node_js

node:
  - "0.6"

before_install:
  - sudo apt-get install python-software-properties -y
  - sudo add-apt-repository ppa:eyecreate/haxe -y
  - sudo apt-get update
  - sudo apt-get install haxe -y --force-yes
  - mkdir ~/haxelib
  - haxelib setup ~/haxelib
  - haxelib install openfl
  - haxelib install openfl-tools
  - haxelib install format
  - haxelib install munit
  - git clone https://github.com/openfl/openfl-validation ~/openfl-validation
  - haxelib dev openfl-html5-dom $(pwd)

script:
  - haxelib run openfl build ~/openfl-validation html5
